### ISSUE TITLE
Get raw IMU data from vive tracker

### ISSUE THREAD

**Issue by pangfumin** [cnlohr/libsurvive#102]
Hi , thank you for sharing this interesting reverse  engineering.
I am also finding a lightweight way to using raw data from vive tracker. 
From [https://apollack11.github.io/vive-tracker-localization.html](url) I know libsurvive is already able to get traker's angle to lighthouse, I want to know  whether this lib can get raw imu data from the tracker?
IMU data can help improve  high dynamic motion estimate. So I really want to know is there a way to get imu data.

Thank you again.

**Comment by ChristophHaag** [comment]
Yes.

The example in the readme only uses the callback for the pose but I just tried the callback for the IMU and it seems okay:
```c
#include <stdio.h>
#include <string.h>
#define FLT double
#include <survive.h>

void testprog_imu_process(SurviveObject * so, int mask, FLT * accelgyromag, uint32_t timecode, int id)
{
	survive_default_imu_process(so, mask, accelgyromag, timecode, id);
	if (strcmp(so->codename, "HMD") == 0) {
		printf("IMU: [%s] [% 08.8f,% 08.8f,% 08.8f] [% 08.8f,% 08.8f,% 08.8f]\n", so->codename, accelgyromag[0], accelgyromag[1], accelgyromag[2], accelgyromag[3], accelgyromag[4], accelgyromag[5]);
	}
}

int main(int argc, char** argv) {
	struct SurviveContext *ctx = survive_init( 0 );
	survive_install_imu_fn(ctx, testprog_imu_process);
	while(survive_poll(ctx) == 0) {
	}
	return 0;
}
```
There's 2* 3values that seem to come directly from the vive. I think the first three are acceleration and the second three are orientation.
