### ISSUE TITLE
Lighthouse 2.0

### ISSUE THREAD

**Issue by patxikuku** [cnlohr/libsurvive#145]
Hello,

I saw that you did some work in understanding the new base stations.
[https://github.com/cnlohr/esptracker/issues/1](https://github.com/cnlohr/esptracker/issues/1)
I wanted to know if you added their support to libsurvive.

**Comment by jdavidberger** [comment]
Basic support for LH2 is now in the master branch of libsurvive. Currently it's early stages; so it isn't perfect and calibration is still a work in progress.
