### ISSUE TITLE
Using libsurvive for drone positioning

### ISSUE THREAD

**Issue by goldarte** [cnlohr/libsurvive#147]
Hi!

We got the HTC Vive Kit for a several weeks for experiments and successfully used your library for positioning of the drone! Here is the modified ROS wrapper of libsurvive (with YouTube video examples of flights): https://github.com/sfalexrog/roslibsurvive.

Thanks for the library! Waiting for support of the 2nd generation of HTC LightHouses :)

**Comment by jdavidberger** [comment]
This is awesome! Let me know if there are any more videos of it!

Check out the latest commits; gen2 support is in and should work

**Comment by goldarte** [comment]
We are in the process of buying HTC Vive Lighthouses v2.0, so when we get the new result, I write here.
