### ISSUE TITLE
Disambiguation with watchmen

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/libsurvive#15]
Need to figure this disambiguation with the watchmen thing out.  Syncing is frequently wrong.
![untitled](https://cloud.githubusercontent.com/assets/2748168/22235187/f9bd9964-e1cb-11e6-83a3-5d643ffeae37.png)

**Comment by jpicht** [comment]
What does that graph actually show?

**Comment by cnlohr** [comment]
It shows that when a base station is scanning, most of the time, the value of the scanned time is the same, but, every now and then it gets a read time much earlier.  In fact this happens almost 30% of the time.  I believe the second peak is the correct one.  But, for some reason the disambiguator is sometimes saying "no it happened at 380000 ticks, not 380400 ticks!" which is wrong.  Forgot to mention: X axis is ticks/4.
