### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [cnlohr/libsurvive#156]
Would you like to add more error handling for return values from functions like the following?
- [calloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [DriverRegUDP](https://github.com/cnlohr/libsurvive/blob/e56767faef5c8131a5528a4487d3e20921c3cd81/src/driver_udp.c#L100)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [qr_solve](https://github.com/cnlohr/libsurvive/blob/0af263ad5f98d0655951c62ebdf791e53bbad437/src/barycentric_svd/barycentric_svd.c#L259)

**Comment by jdavidberger** [comment]
Fixed in 451bae65a45b85ec3b87821328e78b3f6959c9a9

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/cnlohr/libsurvive/commit/451bae65a45b85ec3b87821328e78b3f6959c9a9 "Addition of an allocation check wrapper").

-----

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
