### ISSUE TITLE
Using the existing framework (Issue for Livestream #6)

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/libsurvive#16]
This is a placeholder issue for the livestream 6 that happened on Feb 4, 2017.

**Comment by MagicInventor** [comment]
k

**Comment by cnlohr** [comment]
Use fcal data.   Factory calibration data of base stations: https://github.com/nairol/LighthouseRedox/blob/master/docs/Base%20Station.md#base-station-info-block

**Comment by cnlohr** [comment]
For completeness sake, posting link here: https://www.youtube.com/watch?v=JsfkNRFkFM4&t=12100s
