### ISSUE TITLE
Agenda for Dec 17 Livestream

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/libsurvive#5]
* Get point and normals for watchmen
* Visualize lighthouse probability data in voxeltastic
* Improve watchman disambiguator
* Collect more data as people want it

**Comment by nairol** [comment]
Regarding the calibration data of the controllers. You should be able to use the same method to download them as with the HMD.
Here is some example data from my Vive and an explanation how to do this using "lighthouse_console" on Windows: https://github.com/nairol/LighthouseRedox/tree/master/data/calibration%20data

**Comment by cnlohr** [comment]
What is up with the mura correction stuff?? That looks wicked! == per-pixel brightness calibration.  People in chat are describing it as a correction for the AMOLED dispaly?

**Comment by cnlohr** [comment]
@nairol  - how do I actually get the profile from the controllers? I've tried it wirelessly.  Does it not work wirelessly?

**Comment by nairol** [comment]
Never tried it myself. It should be able to get the data wirelessly because that is what SteamVR does every time you start it.
I guess I'll have to sniff the USB traffic again. I'll report back once I know more...

**Comment by nairol** [comment]
Pcaps: https://github.com/nairol/LighthouseRedox/tree/master/data/Vive%20USB%20protocol/System

**Comment by cnlohr** [comment]
Now, I wish I could understand what's up with that control out message.  It's so jank.

**Comment by cnlohr** [comment]
* Got points/normals for watchmen after livestream by getting config now.
* Visualized
* People are working on a better disambiguator
* Will be collecting more data!  

closing issue.
