### ISSUE TITLE
Read watchman configuration

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/libsurvive#7]
We need a way of reading the configuration from the watchmen.  Right now I'm stuck at sending the commands needed to read from them via libusb.  It seems that there is a control_out message that's being sent that seems to trigger a read config from the controllers.

**Comment by bjj** [comment]
You have to retry the failed USB commands.  They will STALL (which will be an error on the host) while the radio round-trip is complete.  Then they will succeed.

**Comment by cnlohr** [comment]
Hmm... I can totally retry, since it's what I'm usually doing for other operations like reading the HMD config, but, what is kinda trippin' me out is this control message found in @nairol's dump.

![watchmanodd](https://cloud.githubusercontent.com/assets/2748168/21296917/64587cb6-c544-11e6-932d-61123b4a8024.png)


I guess I'll just try spamming things more :-p

**Comment by bjj** [comment]
It's just a GET FEATURE request to an endpoint whose descriptors call for
report IDs.

**Comment by cnlohr** [comment]
It looks like in the packet dump the data from/to was switched around.  When I ignore that and just treat it like a normal control message everything's fine and I can pull the data.
